repos:
  - repo: local
    hooks:
      - id: phase1-status-sync
        name: Ensure PHASE1 status block is current
        entry: uv run tools/sync_phase1.py --check
        language: system
        pass_filenames: false
